(()=>{
const key='portfolio-edit:'+location.pathname,editSel='h1,h2,h3,p,dt,dd,small,.tag,.eyebrow,.row span,.skill-number,.game-number,.visual-label',layoutSel='.hero,.section,.project-card,.skill-card,.game-card,.chapter,.card,.block,footer';let on=false,selected=null,history=[];
const roots=()=>[...document.querySelectorAll('main,footer')],snap=()=>roots().map(x=>x.innerHTML),remember=()=>{history.push(snap());if(history.length>30)history.shift()};
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved)roots().forEach((x,i)=>{if(saved[i]!=null)x.innerHTML=saved[i]})}catch(e){console.warn(e)}
const panel=document.createElement('aside');panel.className='editor-panel';panel.innerHTML=`<div class="editor-head"><strong>편집 도구</strong><span data-status>요소를 선택하세요</span></div><div class="editor-controls"><button data-do="underline"><u>밑줄</u></button><label>글자색<input data-do="color" type="color" value="#17233f"></label><label>형광펜<input data-do="highlight" type="color" value="#fff176"></label></div><div class="editor-controls"><label>글자 크기<select data-do="font"><option value="">기본</option>${[12,14,16,18,20,24,28,32,40,48,64].map(x=>`<option>${x}</option>`)}</select></label><label>너비(px)<input data-do="width" type="number" min="40" step="10"></label><label>높이(px)<input data-do="height" type="number" min="20" step="10"></label></div><div class="editor-controls"><button data-do="size-reset">크기 초기화</button><button data-do="image-add">이미지 삽입</button><button data-do="image-remove">이미지 제거</button></div><div class="editor-controls"><button data-do="save">저장</button><button data-do="export">HTML 내보내기</button><button data-do="undo">되돌리기</button><button class="editor-danger" data-do="reset">저장 초기화</button></div><input data-do="file" type="file" accept="image/*"><p class="editor-help">텍스트나 요소를 선택하세요. 레이아웃 우하단을 드래그해서 크기를 바꿀 수도 있습니다.</p><p class="editor-message" role="status"></p>`;document.body.append(panel);
const toggle=document.createElement('button');toggle.className='editor-toggle';toggle.textContent='편집 모드';document.body.append(toggle);const status=panel.querySelector('[data-status]'),message=panel.querySelector('.editor-message'),file=panel.querySelector('[data-do=file]');
const note=x=>{message.textContent=x;clearTimeout(note.t);note.t=setTimeout(()=>message.textContent='',2200)},choose=x=>{selected?.classList.remove('editor-selected');selected=x;selected?.classList.add('editor-selected');status.textContent=x?(x.alt||x.textContent||x.tagName).trim().slice(0,24):'요소를 선택하세요'},prepare=()=>{document.querySelectorAll(editSel).forEach(x=>{if(!panel.contains(x)){x.dataset.editable='';x.contentEditable=on;x.spellcheck=on}});document.querySelectorAll(layoutSel).forEach(x=>x.classList.toggle('editor-layout',on))};
const style=(prop,value)=>{if(!selected)return note('텍스트를 먼저 선택하세요.');remember();const s=getSelection();if(s&&!s.isCollapsed&&selected.contains(s.anchorNode)){const r=s.getRangeAt(0),span=document.createElement('span');span.style[prop]=value;try{r.surroundContents(span)}catch{selected.style[prop]=value}}else selected.style[prop]=value;note('서식을 적용했습니다.')};
const exportHTML=()=>{const copy=document.documentElement.cloneNode(true);copy.querySelectorAll('.editor-panel,.editor-toggle').forEach(x=>x.remove());copy.querySelector('body')?.classList.remove('editor-on');copy.querySelectorAll('[contenteditable],[data-editable]').forEach(x=>{x.removeAttribute('contenteditable');x.removeAttribute('data-editable');x.removeAttribute('spellcheck')});copy.querySelectorAll('.editor-selected,.editor-layout').forEach(x=>x.classList.remove('editor-selected','editor-layout'));const html='<!doctype html>\n'+copy.outerHTML,blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=location.pathname.split('/').pop()||'index.html';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);note(link.download+' 파일을 내보냈습니다.')};
toggle.onclick=()=>{on=!on;document.body.classList.toggle('editor-on',on);toggle.textContent=on?'편집 종료':'편집 모드';if(!on)choose(null);prepare()};
document.addEventListener('click',e=>{if(!on||panel.contains(e.target)||e.target===toggle)return;const x=e.target.closest('img,'+editSel+','+layoutSel);if(x){e.preventDefault();e.stopPropagation();choose(x)}},true);
panel.addEventListener('click',e=>{const a=e.target.closest('[data-do]')?.dataset.do;if(!a)return;const layout=selected?.closest(layoutSel);if(a==='underline')style('textDecoration',selected?.style.textDecoration==='underline'?'none':'underline');if(a==='size-reset'){if(!layout)return note('레이아웃을 선택하세요.');remember();layout.style.width=layout.style.height='';note('크기를 초기화했습니다.')}if(a==='image-add')file.click();if(a==='image-remove'){const img=selected?.matches('img')?selected:selected?.querySelector?.('img');if(!img)return note('이미지를 선택하세요.');remember();choose(img.parentElement);img.remove();note('이미지를 제거했습니다.')}if(a==='save'){try{localStorage.setItem(key,JSON.stringify(snap()));note('브라우저에 저장했습니다.')}catch{note('이미지가 커서 저장하지 못했습니다.')}}if(a==='export')exportHTML();if(a==='undo'){const p=history.pop();if(!p)return note('되돌릴 변경이 없습니다.');roots().forEach((x,i)=>x.innerHTML=p[i]);choose(null);prepare();note('되돌렸습니다.')}if(a==='reset'&&confirm('저장된 편집 내용을 초기화할까요?')){localStorage.removeItem(key);location.reload()}});
panel.addEventListener('input',e=>{const a=e.target.dataset.do;if(a==='color')style('color',e.target.value);if(a==='highlight')style('backgroundColor',e.target.value);if(a==='font'&&e.target.value)style('fontSize',e.target.value+'px');if(a==='width'||a==='height'){const x=selected?.closest(layoutSel);if(!x)return note('레이아웃을 선택하세요.');remember();x.style[a]=e.target.value?e.target.value+'px':'';note('크기를 변경했습니다.')}});
file.onchange=()=>{const f=file.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{remember();if(selected?.matches('img'))selected.src=r.result;else{const img=document.createElement('img');img.src=r.result;img.alt=f.name;img.className='editor-image';if(selected)selected.insertAdjacentElement('afterend',img);else document.querySelector('main').append(img);choose(img)}file.value='';note('이미지를 삽입했습니다.')};r.readAsDataURL(f)};
})();
